- type: department
  id: SyndicateCommand
  name: department-syndicate-command
  description: department-syndicate-command-description
  color: "#d9a336"
  roles:
  - SyndicateCommandOperator
  - SyndicateCommandAgent
  - SyndicateCommandOfficer
  - SyndicateCommandOfficial
  - CBURNSyndicate
  - ERTLeaderSyndicate
  - ERTChaplainSyndicate
  - ERTJanitorSyndicate
  - ERTMedicalSyndicate
  - ERTSecuritySyndicate
  - ERTEngineerSyndicate
  editorHidden: true
  weight: 120
