- type: entity
  parent: MarkerBaseStarcup # starcup
  id: DecalSpawnerBase
  name: Decal Spawner
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: shadowgreen # starcup
    - state: green
    - sprite: Markers/cross.rsi
      state: decal

