- type: entity
  parent: CrateGenericSteel
  id: CrateServiceMixedLights
  name: mixed lights crate
  description: An assortment of lights of various temperature ratings; perfect for the aspiring brutalist or just making a room cozy.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLightsWarm
        - id: BoxLightsCold

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceVioletLights
  name: ultraviolet lighttubes crate
  description: A box of near-ultraviolet lights for the parties that really want to go all-out.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLightsViolet

- type: entity
  parent: CratePlastic
  id: CrateServiceLunchboxEmpty
  name: empty lunchbox delivery
  description: Sixteen empty lunchboxes, two for each department, for the chef who wants to feed the station in style.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: LunchboxGeneric
          amount: 2
        - id: LunchboxCommandSyndie
          amount: 2
        - id: LunchboxSecurity
          amount: 2
        - id: LunchboxMedical
          amount: 2
        - id: LunchboxLogistics
          amount: 2
        - id: LunchboxEngineering
          amount: 2
        - id: LunchboxEpistemics
          amount: 2
        - id: LunchboxService
          amount: 2
        - id: LunchboxSyndicate
          prob: 0.05
        - id: LunchboxJustice
          prob: 0.005
