
#Misc outfit startingGear definitions.

# Laika sec glasses

#- type: startingGear
#  id: MobSecDogLaikaGear
#  equipment:
#    eyes: ClothingEyesGlassesSecurity
#starcup: commenting out - therapy dogs do not need sec glasses
