using Content.Client.UserInterface.Controls;
using Content.Shared._NF.CCVar; // starcup
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // starcup
using Robust.Shared.Utility;

namespace Content.Client._NF.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRespawnRulesWindow : FancyWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!; // starcup
        
        public PanelContainer RulesContainer => TextContainer;
        public RichTextLabel RulesLabel = new() { Margin = new Thickness(5, 5, 5, 5) };
        public Button RespawnButton => ConfirmRespawnButton;

        public GhostRespawnRulesWindow()
        {
            RobustXamlLoader.Load(this);

            // begin starcup: put respawn cooldown in popup
            var respawnSeconds = _cfgManager.GetCVar(NFCCVars.RespawnTime);
            var respawnMinutes = TimeSpan.FromSeconds(respawnSeconds).TotalMinutes;
            // end starcup

            var message = new FormattedMessage();
            message.AddMarkup(Loc.GetString("ghost-respawn-rules-window-rules", ("minutes", $"{respawnMinutes:f0}"))); // starcup: put respawn cooldown in popup
            RulesLabel.SetMessage(message);
            RulesContainer.AddChild(RulesLabel);
            RulesLabel.SetPositionFirst();

            RespawnButton.OnPressed += _ => Close();
        }
    }
}
