# Several Delta-V Justice phrases have been moved here.
# Not all are currently implemented, but they have localizations already if we should decide to enable them.
- type: quickPhrase
  id: PhraseWitness
  parent: BaseSecuritySubjectPhrase
  text: phrase-witness

- type: quickPhrase
  id: PhraseEvidence
  parent: BaseSecuritySubjectPhrase
  text: phrase-evidence

- type: quickPhrase
  id: PhraseCase
  parent: BaseSecuritySubjectPhrase
  text: phrase-case

#- type: quickPhrase
#  id: PhraseSue
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-sue

#- type: quickPhrase
#  id: PhraseCourtroomTimer
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-courtroom-timer

#- type: quickPhrase
#  id: PhraseBailiff
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-bailiff

- type: quickPhrase
  id: PhraseSentence
  parent: BaseSecuritySubjectPhrase
  text: phrase-sentence

- type: quickPhrase
  id: PhraseDefendant
  parent: BaseSecuritySubjectPhrase
  text: phrase-defendant

#- type: quickPhrase
#  id: PhrasePlaintiff
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-plaintiff

- type: quickPhrase
  id: PhraseVictim
  parent: BaseSecuritySubjectPhrase
  text: phrase-victim

- type: quickPhrase
  id: PhraseDefense
  parent: BaseSecuritySubjectPhrase
  text: phrase-defense

- type: quickPhrase
  id: PhraseProsecution
  parent: BaseSecuritySubjectPhrase
  text: phrase-prosecution

#- type: quickPhrase
#  id: PhraseStatement
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-statement

#- type: quickPhrase
#  id: PhraseGavel
#  parent: BaseSecuritySubjectPhrase
#  text: phrase-gavel

- type: quickPhrase
  id: PhraseCharge
  parent: BaseSecuritySubjectPhrase
  text: phrase-charge

- type: quickPhrase
  id: PhraseGuilty
  parent: BaseSecuritySubjectPhrase
  text: phrase-guilty

- type: quickPhrase
  id: PhraseNotGuilty
  parent: BaseSecuritySubjectPhrase
  text: phrase-not-guilty

- type: quickPhrase
  id: PhraseObjection
  parent: BaseSecuritySubjectPhrase
  text: phrase-objection

- type: quickPhrase
  id: PhraseNeedMoreTime
  parent: BaseSecuritySubjectPhrase
  text: phrase-request-time

- type: quickPhrase
  id: PhraseYourHonor
  parent: BaseSecuritySubjectPhrase
  text: phrase-your-honor

- type: quickPhrase
  id: PhraseParole
  parent: BaseSecuritySubjectPhrase
  text: phrase-request-time
